export const FETCH_DATA = 'EMPIRES/FETCH_CIVILIZATIONS';
export const REQUEST_DATA = 'EMPIRES/REQUEST_CIVILIZATIONS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
